---
  extends: "@enspirit/eslint-config-node"
  env:
    node: true
    mocha: true
    es6: true
  parser: "@typescript-eslint/parser"
  plugins:
    - "@typescript-eslint"
  parserOptions:
    sourceType: module
    ecmaFeatures:
      modules: true
  rules:
    "@typescript-eslint/no-unused-vars": ["error"]
