services:

  seshat:
    build: .
    command: npm run dev
    environment:
      S3_ENDPOINT: https://minio
      # we are using self signed certs in development/test
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/app/src
      - ./examples:/home/app/examples
      - ./tmp:/home/app/tmp

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key
    command: minio server --console-address 0.0.0.0:9001 --address ":443" /data
    volumes:
      - ./volumes/s3:/data
      - ./minio/certs:/root/.minio/certs

  gcs:
    image: fsouza/fake-gcs-server
    command: ["-scheme", "http"]
    ports:
      - 4443:4443
    volumes:
      - ./volumes/gcs:/data
