services:

  seshat:
    build:
      context: ./
    command: pnpm run dev
    environment:
      S3_ENDPOINT: https://minio
      # we are using self signed certs in development/test
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./services/server/src:/home/app/services/server/src
      - ./services/server/examples:/home/app/services/server/examples
      - ./packages/client/src:/home/app/packages/client/src
      - ./packages/vue/src:/home/app/packages/vue/src
      - ./tmp:/home/app/tmp

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key
    command: minio server --console-address 0.0.0.0:9001 --address ":443" /data
    volumes:
      - ./volumes/s3:/data
      - ./minio/certs:/root/.minio/certs

  gcs:
    image: fsouza/fake-gcs-server
    command: ["-scheme", "http"]
    ports:
      - 4443:4443
    volumes:
      - ./volumes/gcs:/data

  clamav:
    image: clamav/clamav:1.2

