services:

  minio:

    image: minio/minio
    volumes:
      - ./volumes/minio:/data
    command:
      - server
      - /data
      - --console-address
      - :9001
    ports:
      - 9000:9000
      - 9001:9001