version: '3.8'

services:

  seshat:
    image: seshat/seshat:${DOCKER_TAG}
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      ./env/devel.env
    user: "1000:1000"
    volumes:
      - ./src:/home/app/webapp/src
      - ./tests:/home/app/webapp/tests
      - ./config:/home/app/webapp/config
      - ./babel.config.json:/home/app/webapp/babel.config.json
      - ./.eslintrc.js:/home/app/webapp/.eslintrc.js
      - ./package.json:/home/app/webapp/package.json
      - ./volumes/seshat/:/home/app/webapp/tmp/

  webspicy:
    image: seshat/webspicy:${DOCKER_TAG}
    # Keep it on to speed up consecutive tests run
    entrypoint: /bin/sh
    # keep it running
    tty: true
    depends_on:
      - seshat
    env_file:
      ./webspicy/env/devel.env
    user: "1000:1000"
    volumes:
      - ./webspicy/support:/home/app/support
      - ./webspicy/tests:/home/app/tests
      - ./webspicy/config.rb:/home/app/config.rb
      - ./webspicy/schema.fio:/home/app/schema.fio
      - ./volumes/seshat/:/home/app/tmp/

  fake-gcs-server:
    image: fsouza/fake-gcs-server
    ports:
      - 8080:8080
    user: "1000:1000"
    volumes:
      - ./volumes/seshat/gcs:/data/
    command: ["-scheme", "http", "-port", "8080", "-external-url", "http://fake-gcs-server:8080", "-backend", "filesystem"]
