version: '3.8'

services:

  seshat:
    image: seshat/seshat
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      ./env/devel.env
    volumes:
      - ./src:/home/app/src
      - ./tests:/home/app/tests
      - ./config:/home/app/config
      - ./babel.config.json:/home/app/babel.config.json
      - ./.eslintrc.js:/home/app/.eslintrc.js
      - ./package.json:/home/app/package.json
      - ./volumes/seshat/:/home/app/tmp/

  webspicy:
    image: seshat/webspicy
    # Keep it on to speed up consecutive tests run
    command:
      tail -f /dev/null
    depends_on:
      - seshat
    env_file:
      ./webspicy/env/devel.env
    volumes:
      - ./webspicy/support:/home/app/support
      - ./webspicy/tests:/home/app/tests
      - ./webspicy/config.rb:/home/app/config.rb
      - ./webspicy/schema.fio:/home/app/schema.fio
      - ./volumes/seshat/:/home/app/tmp/
