---
  name: |-
    GET /{strategy}/{object}

  url: |-
    /{strategy}/{object}

  services:
  - method: |-
      GET

    description: |-
      Allows retrieving a file, with the Cache-Control header configured on
      RetrieveObjects

    preconditions:
      - An object with that name exists on the bucket

    postconditions:
      - (x) It supports the Last-Modified/If-Modified-Since caching protocol
      - ( ) It sets the Cache-Control header as expected

    input_schema: |-
      {
        strategy: String
        object: String
      }

    output_schema: |-
      {
        ...: String | .
      }

    error_schema: |-
      Error

    examples:

      - description: |-
          FOR: It sets the Cache-Control header as expected
        params:
          strategy: cached
          object: test.json
        expected:
          content_type: application/json
          status: 200
          headers:
            Cache-Control: private, max-age=86400, must-revalidate

      - description: |-
          FOR: It sets the Cache-Control header as expected
        params:
          strategy: no-cache
          object: test.json
        expected:
          content_type: application/json
          status: 200
          headers:
            Cache-Control: no-cache
