name: Integration

on:
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:

      # - uses: act10ns/slack@v1
      #   with:
      #     status: starting
      #     channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - run: make -j images
      - run: make up
      - run: ls -l
      - name: Running tests
        run: make tests
        id: tests

      - run: make lint

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
