name: Running tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: 2.7

      - run: make ci
        env:
          NODE_VERSION: ${{ matrix.node-version }}

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
