name: Running tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Set up node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - run: make ci

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
